// Every TSM interactive, grouped for the landing page. status: 'live' | 'soon'.
// Each tool lives at tools/<slug>/ with index.html and thumb.svg.
// sites: which published sites show an entry ('tsm' = Interactive Deterrence, 'deterrence' = Interactive Deterrence).
// Entries without `sites` appear on both. The build writes the site id into site.js.
import { SITE } from './site.js';

const CATEGORY_LIST = [
  { id: 'trackers', name: 'Live trackers', blurb: 'Taiwan Strait tracker data you can filter and explore.' },
  { id: 'crisis', name: 'Crises & exercises', blurb: 'How PLA pressure campaigns unfold, and how to read the warning signs.' },
  { id: 'geo', name: 'Indo-Pacific geography', blurb: 'Island chains, chokepoints, contested features and the cables beneath them.' },
  { id: 'models', name: 'Force & wargame models', siteName: { deterrence: 'War Games and Simulations' },
    siteBlurb: { deterrence: 'Wargames to play, from Kharg Island to the Berlin Airlift, and models of kill chains and budgets.' },
    blurb: 'Hands-on models of kill chains, blockades, mines and defense budgets.',
    subs: [{ id: 'wargames', name: 'Wargames', blurb: 'Play a side: raids, island assaults, submarine hunts, matrix games and the Berlin Airlift.' },
      { id: 'budget', name: 'Budget and Logistics', blurb: 'Budgets, kill chains, interceptor stocks and mine clearance.' }] },
  { id: 'narrative', name: 'Narrative & rhetoric', blurb: 'What Beijing says and how it spreads through state media.' },
  { id: 'classroom', name: 'Classroom', blurb: 'Teaching tools for courses on deterrence, strategy and cross-Strait history.' },
  { id: 'public', name: 'Public explainers', blurb: 'Short, shareable pieces for a general audience.' },
  { id: 'gametheory', name: 'Game theory', sites: ['deterrence'],
    blurb: 'Game-theory models of bargaining, signaling, brinkmanship, deterrence and inspection, and the markets that price war.' },
  { id: 'nuclear', name: 'Nuclear weapons & arms control', sites: ['deterrence'],
    blurb: 'Arsenals, treaties and escalation, country by country and crisis by crisis.',
    // Subsections: tools pick one with `sub: { nuclear: '<id>' }`.
    subs: [{ id: 'facts', name: 'Fact Sheets', blurb: 'Sourced data you can browse: arsenals, tests, doctrine, treaties and proliferation.' },
      { id: 'playground', name: 'Models / Nuclear Playground', blurb: 'Models to play with: warhead ambiguity, entanglement, crisis stability and escalation.' }] },
  { id: 'regions', name: 'Regions', sites: ['deterrence'],
    blurb: 'Wars and flashpoints by region: Russia and Ukraine, the Middle East and the Indo-Pacific.',
    subs: [{ id: 'ukraine', name: 'Russia & Ukraine', blurb: 'The war in data: strikes, air defense, nuclear signaling and support.' },
      { id: 'mideast', name: 'Middle East', blurb: 'Chokepoints, shipping and missile exchanges from the Red Sea to Hormuz.' },
      { id: 'indopacific', name: 'Indo-Pacific', locked: true, blurb: 'Taiwan Strait trackers, exercise replays and wargames.' }] },
  { id: 'narratives', name: 'Disinfo and Narratives', sites: ['deterrence'],
    blurb: 'How false stories spread and stick, and what governments say, phrase by phrase.',
    subs: [{ id: 'disinfo', name: 'Disinformation & cognitive warfare', blurb: 'How false stories spread and stick, and how belief updating can be attacked.' },
      { id: 'rhetoric', name: 'State rhetoric', blurb: 'What governments say, week by week: China, Russia and others, phrase by phrase.' }] },
  // Taiwan tools behind the second password. Hidden as a top-level section; shown as Regions › Indo-Pacific.
  { id: 'tsm', name: 'Indo-Pacific', sites: ['deterrence'], locked: true, hidden: true,
    blurb: 'Taiwan Strait trackers, exercise replays and wargames.' },
  // Tools marked `dev: true` show only here (never in their other categories) and need their own password.
  // `sealed`: on the published site their registry entries are encrypted (DEV_SEALED below), so the section
  // itself asks for the password before it lists anything.
  { id: 'dev', name: 'Coming Soon', sites: ['deterrence'], locked: true, sealed: true,
    blurb: 'Tools still being built and checked.',
    subs: [{ id: 'games', name: 'Coming Soon games', blurb: 'New games to play-test before they go public.' }] },
];
// siteName and siteBlurb rename or re-describe a section on one site only.
export const ALL_CATEGORIES = CATEGORY_LIST.map(c => ({ ...c, name: (c.siteName && c.siteName[SITE]) || c.name,
  blurb: (c.siteBlurb && c.siteBlurb[SITE]) || c.blurb }));

export const ALL_TOOLS = [
  { slug: 'strait-layers', siteCat: { deterrence: 'tsm' }, also: ['regions'], sub: { regions: 'indopacific' }, cat: 'models', title: 'Strait Layers', status: 'live',
    blurb: 'PLA A2/AD rings, the kill chain behind them, a PLA crossing, and salvo math.' },
  { slug: 'ccg-grayzone', sites: ['tsm'], cat: 'trackers', title: 'CCG Gray-Zone Map', status: 'live',
    blurb: 'Every China Coast Guard incident the Taiwan Security Monitor has recorded since June 2024, on a map with a year selector and time slider.' },
  { slug: 'transit-response', siteCat: { deterrence: 'tsm' }, also: ['regions'], sub: { regions: 'indopacific' }, cat: 'trackers', title: 'Transit Response Explorer', status: 'live',
    blurb: 'Pick an allied Strait transit and see how the PLA answered in the days around it.' },
  { slug: 'strait-snapshot', sites: ['tsm'], cat: 'trackers', title: 'Strait Snapshot Live', status: 'live',
    blurb: 'The six monthly Strait Snapshot figures as live charts for any month of 2026.' },
  { slug: 'arms-backlog', sites: ['tsm'], cat: 'trackers', title: 'Arms Sales Backlog', status: 'live',
    blurb: 'Every U.S. arms sale Taiwan is still waiting for, from notification to delivery, with the backlog total over time.' },
  { slug: 'dark-fleet', sites: ['tsm'], cat: 'trackers', title: 'Dark Fleet Viewer', status: 'live',
    blurb: 'Chinese-flag AIS tracks around Taiwan from the Taiwan Security Monitor\'s AIS database, when they go dark, and two years of coast guard and militia activity.' },
  { slug: 'flight-atlas', sites: ['tsm'], cat: 'trackers', title: 'PLA Flight-Path Atlas', status: 'live',
    blurb: "Which sectors of Taiwan's ADIZ PLA aircraft entered, day by day since 2020, read from the text of MND's daily reports." },
  { slug: 'balloon-tracker', sites: ['tsm'], cat: 'trackers', title: 'Balloon Tracker', status: 'live',
    blurb: "PRC balloons reported by Taiwan's MND: where MND placed them, when they came, and how they cluster in winter." },
  { slug: 'kinmen-closeup', sites: ['tsm'], cat: 'trackers', title: 'Kinmen Close-Up', status: 'live',
    blurb: "China Coast Guard incursions at Kinmen, 2024\u201326, mapped inside Taiwan's officially published boundary, with the hulls that keep coming back." },
  { slug: 'joint-sword', siteCat: { deterrence: 'tsm' }, also: ['regions'], sub: { regions: 'indopacific' }, cat: 'crisis', title: 'Anatomy of an Exercise', status: 'live',
    blurb: 'Major PLA exercises around Taiwan, replayed day by day with published zones, daily counts and statements.' },
  { slug: 'escalation-ladder', sites: ['tsm'], cat: 'crisis', title: 'Escalation Ladder', status: 'live',
    blurb: 'A hypothetical Kinmen quarantine crisis: choose Taipei, Washington and Tokyo moves and watch the rungs light up.' },
  { slug: 'coercion-options', sites: ['tsm'], cat: 'crisis', title: 'Quarantine, Blockade, Invasion', status: 'live',
    blurb: 'Five coercive options side by side, from gray zone to invasion: legal status, warning, costs and triggers.' },
  { slug: 'warning-board', siteCat: { deterrence: 'tsm' }, also: ['regions'], sub: { regions: 'indopacific' }, cat: 'crisis', title: 'Indicators & Warning Board', status: 'live',
    blurb: 'Exercises light up the board too. Set 33 sourced indicators and see what separates a drill from preparation for war.' },
  { slug: 'island-chains', sites: ['tsm'], cat: 'geo', title: 'Island Chains & Access', status: 'live',
    blurb: 'First and second island chains, U.S. and allied basing, and what can reach what.' },
  { slug: 'chokepoints', sites: ['tsm'], cat: 'geo', title: 'Chokepoint Dashboard', status: 'live',
    blurb: 'Close Malacca, Luzon or the Taiwan Strait and watch the tanker reroute, with the added days and cost.' },
  { slug: 'scs-features', sites: ['tsm'], cat: 'geo', title: 'South China Sea Features', status: 'live',
    blurb: 'Who holds which reef, what China built, and what the 2016 tribunal ruled.' },
  { slug: 'undersea-cables', sites: ['tsm'], cat: 'geo', title: 'Taiwan\'s Undersea Cables', status: 'live',
    blurb: 'Where Taiwan\'s submarine cables land, and which islands go dark when you cut them.' },
  { slug: 'japan-view', sites: ['tsm'], cat: 'geo', title: "Japan's View: PLA Near Japan", status: 'live',
    blurb: "Every PLA Navy crossing of Japan's straits that Tokyo reported in 2025\u201326, by strait, direction and hull number, set against Taiwan's daily counts." },
  { slug: 'crossing-windows', siteCat: { deterrence: 'tsm' }, also: ['regions'], sub: { regions: 'indopacific' }, cat: 'geo', title: 'Crossing Windows', status: 'live',
    blurb: 'Thirty years of Taiwan Strait wind, wave, fog and typhoon records, tested against sea-state limits you set: which weeks allowed an amphibious crossing, and how the claimed April and October windows hold up.' },
  { slug: 'energy-blockade', sites: ['tsm'], cat: 'models', title: 'Energy Blockade Clock', status: 'live',
    blurb: 'Set a quarantine or blockade and watch Taiwan\'s LNG, coal and oil stocks run down, and who loses power first.' },
  { slug: 'budget-allocator', sub: { models: 'budget' }, siteBlurb: { tsm: 'Spend Taiwan\'s NT$145.7bn supplementary defense line, or bigger, and test the mix against a notional crossing model.' }, cat: 'models', title: 'Defense Budget Allocator', status: 'live',
    blurb: "Spend Taiwan's NT$145.7bn supplementary defense line, or Japan's, the Philippines' or Poland's real defense budgets, and test the mix against a notional model of an attack on each." },
  { slug: 'mine-warfare', sites: ['tsm'], cat: 'models', title: 'Mine Warfare Simulator', status: 'live',
    blurb: 'Lay a minefield off a generic beach, choose how the PLA clears it, and see what mines do to a landing\'s timing and cost.' },
  { slug: 'kill-chain-builder', game: true, sub: { models: 'budget' }, cat: 'models', title: 'Kill Chain Builder', status: 'live',
    blurb: 'Wire sensors, command nodes and shooters into a kill chain, race the clock against a moving target, then strike nodes to find where it breaks.' },
  { slug: 'penghu-gambit', game: true, siteCat: { deterrence: 'tsm' }, also: ['regions', 'models'], sub: { regions: 'indopacific', models: 'wargames' }, cat: 'models', title: 'Penghu Gambit', status: 'live',
    blurb: "Set Taiwan's defenses and the PLA's plan, play out a notional seizure of Penghu in 12-hour turns with every die roll shown, then run 1,000 games to see what drives the outcome." },
  { slug: 'interceptor-burndown', game: true, sub: { models: 'budget' }, cat: 'models', title: 'Interceptor Burn-down', status: 'live',
    blurb: "Set a daily PRC missile and drone salvo against open-source estimates of Taiwan's Patriot and Tien Kung stocks and see the day each runs dry, how many threats get through, and which assumption matters most." },
  { slug: 'strait-landing', game: true, siteCat: { deterrence: 'tsm' }, also: ['regions', 'models'], sub: { regions: 'indopacific', models: 'wargames' }, cat: 'models', title: 'Strait Landing', status: 'live',
    blurb: "Plan a PLA landing on Taiwan's west coast: send amphibious ships and civilian ferries through real historical sea states, suppress missiles and mines, and race the counterattack to D+3." },
  { slug: 'four-capitals', game: true, sites: ['deterrence'], siteCat: { deterrence: 'tsm' }, also: ['regions', 'models'], sub: { regions: 'indopacific', models: 'wargames' }, cat: 'models', title: 'Four Capitals', status: 'live',
    blurb: 'Play Washington, Taipei, Beijing or Tokyo through a notional eight-month Taiwan crisis: a posture and three moves a month, hidden resolve on every side, scored against your own priorities.' },
  { slug: 'wargame-explorer', siteCat: { deterrence: 'tsm' }, also: ['regions'], sub: { regions: 'indopacific' }, cat: 'models', title: 'Wargame Results Explorer', status: 'live',
    blurb: 'Eight published Taiwan wargames side by side: what each assumed, how it came out, and which assumptions (above all Japan basing and U.S. entry) drive the result, with a page citation for every figure.' },
  { slug: 'rhetoric-heatmap', sub: { narratives: 'rhetoric' }, siteCat: { deterrence: 'narratives' }, cat: 'narrative', title: 'PRC Rhetoric Heatmap', status: 'live',
    blurb: 'Foreign Ministry, Defense Ministry and Taiwan Affairs Office language, week by week.' },
  { slug: 'beijing-decoder', sites: ['tsm'], cat: 'narrative', title: 'Beijing Decoder', status: 'live',
    blurb: 'Paste a PRC statement and see what each formula has signalled before.' },
  { slug: 'narrative-diffusion', sites: ['tsm'], cat: 'narrative', title: 'Narrative Diffusion', status: 'live',
    blurb: 'Follow one PRC talking point from the podium through state media, with the data gaps shown.' },
  { slug: 'markets-vs-analysts', sites: ['deterrence'], cat: 'gametheory', title: 'Markets vs. Analysts', status: 'live',
    blurb: 'What traders pay for a Chinese invasion, blockade or clash, against the PLA activity record.' },
  { slug: 'deterrence-lab', sites: ['tsm'], cat: 'classroom', title: 'Deterrence Lab', status: 'live',
    blurb: 'Audience costs, costly signals and salami tactics as formal models: move the costs and beliefs and watch the equilibrium shift.' },
  { slug: 'history-time-machine', sites: ['tsm'], cat: 'classroom', title: 'Taiwan Time Machine', status: 'live',
    blurb: 'Explore 1895 to today: who controlled Taiwan, Penghu, Kinmen, Matsu and the Dachens, and the treaties, crises and U.S. documents behind each change.' },
  { slug: 'orbat-cards', sites: ['tsm'], cat: 'classroom', title: 'Order of Battle Cards', status: 'live',
    blurb: 'Flip cards for PLA, Taiwanese, Japanese, Philippine and U.S. formations around Taiwan, placed by HQ city, with a student quiz.' },
  { slug: 'packet-builder', sites: ['tsm'], cat: 'classroom', title: 'Briefing Packet Builder', status: 'live',
    blurb: 'Pick a date range and get a printable Taiwan Strait briefing packet: PLA activity against the prior period, coast guard incidents, transits, exercises, PRC statements and every source.' },
  { slug: 'day-in-the-strait', sites: ['tsm'], cat: 'public', title: 'A Day in the Strait', status: 'live',
    blurb: 'One real day of gray-zone pressure around Taiwan, built from the data. Pick any day of 2026.' },
  { slug: 'how-close', sites: ['tsm'], cat: 'public', title: 'How Close Is China?', status: 'live',
    blurb: 'Type a city and see how far it is from Taiwan and from China, with the Taiwan Strait for scale.' },
  { slug: 'dissertation-games', cat: 'gametheory', sites: ['deterrence'], vault: 'dissertation', title: 'Jon Dissertation Games', status: 'live',
    blurb: "Working game trees from Jonathan Walberg's dissertation." },
  { slug: 'nuclear-arsenals', sub: { nuclear: 'facts' }, cat: 'nuclear', sites: ['deterrence'], title: 'Nuclear Arsenals', status: 'live',
    blurb: "Explore eighty years of FAS nuclear warhead estimates for every nuclear-armed state, against the treaties from the NPT to New START's lapse in February 2026." },
  { slug: 'escalation-ladder-kahn', game: true, sub: { nuclear: 'playground' }, cat: 'nuclear', sites: ['deterrence'], title: "Kahn's Escalation Ladder", status: 'live',
    blurb: "Step through nuclear crises from Cuba 1962 to Russia 2022 and India–Pakistan 2025 on Herman Kahn's 44-rung ladder, compare them, and read why the ladder misleads." },
  { slug: 'deterrence-lab-general', game: true, cat: 'gametheory', sites: ['deterrence'], title: 'Deterrence Lab', status: 'live',
    blurb: 'Move the costs and beliefs in three classic deterrence models (audience costs, costly signals and salami tactics) and test them against sourced crises from Fashoda in 1898 to NATO\'s eastern flank in 2016–17.' },
  { slug: 'ukraine-air-war', sub: { regions: 'ukraine' }, cat: 'regions', sites: ['deterrence'], title: "Ukraine's Air War", status: 'live',
    blurb: 'Russian missile and drone launches against Ukraine since 2022, by weapon type, with the share the Ukrainian Air Force reported shooting down.' },
  { slug: 'russia-nuclear-signals', sub: { regions: 'ukraine' }, cat: 'regions', sites: ['deterrence'], title: "Russia's Nuclear Signals", status: 'live',
    blurb: 'Every major Russian nuclear signal since February 2022, sourced and scored by what it changed, set against Western responses and the course of the war.' },
  { slug: 'red-sea-hormuz', sub: { regions: 'mideast' }, cat: 'regions', sites: ['deterrence'], title: 'Red Sea & Hormuz Pulse', status: 'live',
    blurb: 'Daily ship counts through Bab el-Mandeb, Suez and Hormuz from IMF PortWatch, against a sourced timeline of Houthi attacks, strikes, pauses and the 2026 Hormuz mining.' },
  { slug: 'war-markets', cat: 'gametheory', sites: ['deterrence'], title: 'War Markets', status: 'live',
    blurb: 'What prediction markets priced for strikes on Iran, ceasefires and a Russia–NATO clash in 2026, set against how each contract resolved.' },
  { slug: 'crisis-stability', game: true, sub: { nuclear: 'playground' }, cat: 'nuclear', sites: ['deterrence'], title: 'Crisis Stability Calculator', status: 'live',
    blurb: "Set two notional force postures and see Kent and Thaler's first-strike stability index: who gains by striking first, and how MIRVed silos, alert rates and launch under attack move it." },
  { slug: 'entanglement', game: true, sub: { nuclear: 'playground' }, cat: 'nuclear', sites: ['deterrence'], title: 'Nuclear Entanglement', status: 'live',
    blurb: 'Plan a conventional campaign against satellites, command links, launchers and bases that also serve nuclear forces, and watch use-or-lose pressure, misread warning and the fog of war push a notional escalation risk up, then test the fixes the literature proposes.' },
  { slug: 'warhead-ambiguity', game: true, sub: { nuclear: 'playground' }, cat: 'nuclear', sites: ['deterrence'], title: 'Is It a Nuke?', status: 'live',
    blurb: 'Your sensors report an incoming missile that could carry either warhead: update on context, launch site and trajectory, then wait, hit back conventionally or launch on warning, and see how priors and entanglement produce false alarms.' },
  { slug: 'nuclear-tests', sub: { nuclear: 'facts' }, cat: 'nuclear', sites: ['deterrence'], title: 'Every Nuclear Test', status: 'live',
    blurb: 'Explore all 2,056 nuclear tests since Trinity by state, environment, yield and test site, reconciled against the ACA, SIPRI and DOE counts and the treaties that drove testing underground and then stopped it.' },
  { slug: 'declaratory-policy', sub: { nuclear: 'facts' }, cat: 'nuclear', sites: ['deterrence'], title: 'Who Promises What', status: 'live',
    blurb: "No-first-use pledges, security assurances, conditions for use and alert postures for all nine nuclear-armed states, quoted from their own documents and dated, with 'not declared' where no official statement was found." },
  { slug: 'game-theory-gallery', cat: 'gametheory', also: ['deterrence'], sites: ['deterrence'], title: 'Game Theory Gallery', status: 'live',
    blurb: "Move the costs, beliefs and balance of power in eight classic game-theory models of war and cooperation, from Fearon's bargaining range to Schelling's brinkmanship, and watch the equilibrium change, with every result cited to its source." },
  { slug: 'ukraine-support', sub: { regions: 'ukraine' }, cat: 'regions', sites: ['deterrence'], title: 'Who Supports Ukraine', status: 'live',
    blurb: 'Who pledged aid to Ukraine and how much each donor has allocated: military, financial and humanitarian support by donor since 2022, in euros or as a share of GDP, from the Kiel Institute.' },
  { slug: 'proliferation-paths', sub: { nuclear: 'facts' }, cat: 'nuclear', sites: ['deterrence'], title: 'Proliferation Paths', status: 'live',
    blurb: 'Explore 1939 to 2017 to see which states explored, pursued, acquired and gave up nuclear weapons, as three published datasets code it, with every disagreement between them shown.' },
  { slug: 'treaty-tracker', sub: { nuclear: 'facts' }, cat: 'nuclear', sites: ['deterrence'], title: 'Treaty Tracker', status: 'live',
    blurb: 'Twenty nuclear and arms-control treaties, 197 states, 1963 to 2026: explore the years to see who signed, joined, suspended or walked away, with every date traced to a depositary record or official statement.' },
  { slug: 'kharg-island', game: true, sub: { models: 'wargames', regions: 'mideast' }, cat: 'models', also: ['regions'], sites: ['deterrence'], title: 'Kharg Island', status: 'live',
    blurb: "A notional, dice-driven wargame of a U.S. move on Kharg Island, Iran's oil export hub: seize, raid or blockade it, watch every roll, then see how 1,000 games trade success against escalation and oil prices." },
  { slug: 'iran-enrichment', sub: { nuclear: 'facts', regions: 'mideast' }, cat: 'nuclear', also: ['regions'], sites: ['deterrence'], title: "Iran's Enrichment Clock", status: 'live',
    blurb: "Iran's enriched uranium from every IAEA quarterly report since 2016, against the JCPOA limit and quoted breakout estimates, to the June 2025 strikes after which there is no verified figure." },
  { slug: 'hormuz-mcm', game: true, sub: { models: 'budget', regions: 'mideast' }, cat: 'regions', also: ['models'], sites: ['deterrence'], title: 'Hormuz Mine Clearance', status: 'live',
    blurb: 'Set the mines, clutter, forces and threat, and see how long it takes to clear shipping routes through Hormuz and how much risk remains when they are declared clear.' },
  { slug: 'rhetoric-global', sub: { narratives: 'rhetoric', regions: ['ukraine', 'mideast'] }, cat: 'narratives', also: ['regions'], sites: ['deterrence'], title: 'Rhetoric Heatmap: Russia and Beyond', status: 'live',
    blurb: "What the Kremlin and Iran's Foreign Ministry keep saying, week by week since 2021: recurring formulas from 'special military operation' to 'Zionist regime' as a heatmap, with every quote one click from its source." },
  { slug: 'raid-night', game: true, sub: { models: 'wargames', regions: ['ukraine', 'mideast'] }, cat: 'models', also: ['regions'], sites: ['deterrence'], title: 'Raid Night', status: 'live',
    blurb: 'Defend four notional cities through three real-time waves of drones and missiles modelled on real raids, and watch the cost exchange as your interceptors run out.' },
  { slug: 'matrix-game', game: true, sub: { models: 'wargames', regions: 'ukraine' }, cat: 'models', also: ['regions'], sites: ['deterrence'], title: 'Baltic Matrix Game', status: 'live',
    blurb: 'An argument-based matrix wargame of a fictional Narva crisis: argue an action with three reasons, face counter-arguments, and roll 2d6 over six turns.' },
  { slug: 'sub-hunt', game: true, sub: { models: 'wargames' }, cat: 'models', sites: ['deterrence'], title: 'The Hunt', status: 'live',
    blurb: 'Hunt a hidden submarine in the Greenland–Iceland–UK gap: spend each turn\'s effort on buoys, aircraft, helicopter and ship, learn how it moves, and pounce.' },
  { slug: 'fog-of-command', game: true, sub: { models: 'wargames' }, cat: 'models', sites: ['deterrence'], title: 'Fog of Command', status: 'live',
    blurb: 'Defend or attack a fictional valley crossing against a commander who acts only on what it can see. Feint, bait, hit flanks, and spot your artillery with recon.' },
  { slug: 'orbital-denial', game: true, sub: { models: 'wargames', nuclear: 'playground' }, cat: 'models', also: ['nuclear'], sites: ['deterrence'], title: 'Orbital Denial', status: 'live',
    blurb: 'Jam, dazzle, hack or shoot down a notional rival\'s satellites over a 10-month crisis and war, then see what your debris costs both sides for decades, with the escalation risk you ran.' },
  { slug: 'berlin-airlift', game: true, sub: { models: 'wargames' }, cat: 'models', sites: ['deterrence'], title: 'Airlift: Berlin 1948–49', status: 'live',
    blurb: 'Run the Berlin Airlift day by day: juggle C-54s, crews, inspections, runways, fog and the coal-food mix to keep West Berlin supplied, then see your tonnage against the 1948–49 record.' },
];

export const onSite = (x, site = SITE) => !x.sites || x.sites.includes(site);
/** A tool's category on a given site (siteCat overrides cat per site). */
export const catOn = (t, site = SITE) => (t.dev && site === 'deterrence' ? 'dev' : (t.siteCat && t.siteCat[site]) || t.cat);
const ORDER = { deterrence: ['gametheory', 'nuclear', 'regions', 'narratives', 'models', 'tsm', 'dev'] };
// `also` lists extra categories a tool appears in; `cats` is its primary category plus those.
const forSite = t => ({ ...t, cat: catOn(t), cats: catOn(t) === 'dev' ? ['dev'] : [...new Set([catOn(t), ...(t.also || [])])],
  blurb: (t.siteBlurb && t.siteBlurb[SITE]) || t.blurb });
export const TOOLS = ALL_TOOLS.filter(t => onSite(t)).map(forSite);
// Published builds replace this with the Coming Soon entries, encrypted with the Coming Soon password
// (scripts/build_site.py); in the source tree the entries are simply in ALL_TOOLS above.
export const DEV_SEALED = "jNTlLsAC2LT9goQ5BSnIrER2oJJZ//1irVE39LIqJ4A0rkzUJogVqudHf3mKL6cCFoW4pp+NXyB3jTF3O/cqpMco6EnzPd6HPjAuAO+UCF8kYRTObeC0be6x0a2FHiY+n/WAxOW5goNM1rtZ8tSRquVlIS4ratnST8DRFxT+TpL5Q1arpBD/Atd/KzPvkSllZ80NSSHrIxjE/byrES1UfuqXZUw7C2m2eXhmmP/YTNf02/jCO+/A8u2i6t78xnIXg6daW0gf1uPkWTpDVgLoSDMk2WYfvsebUn0G0P7WsEuy69jIsLN3B/MoM+QT/bw6J250nWm8CXNrQ+xcfCq75fmD4C6dRdPjafhpU7DsbPUsYhbWoZlZ3f4UQ62fM0WOXbjvDon3bPr0iTbmv4e5trsDKgffw0nvXV0cXb4cDhdSjhuMJ0ooJB5lqoDjQNIHlxEXmXV/PyE7UT0nbgBhcmLUv77lZqSUFBTcrdHuhN8RLW5SvEVF4Zrh7ZzF+A3IIeTsC1oTTkV/IrcVh7wipxgzWGZV1SEvO4PxwDVDEHrX8Vj1LlKc52USfa7lZJVJWRjtEsZR6WEwNsFjbl3uli4fu4RvbfLo5dzam7QhG8I4mw9D5hO8/K9FpA0rWsK+sgoUKcJ0kIkKTvHYzgW4UZIqhnN+QoSwGUXRlgft04OFnQQ1R29IkKfOpWMarV1SCyRHCksi6xMnPmDnGO/C+ZOGjTQYPPURPUpI5un8wHTQwUDNdNgxYRfevngEFVY605ZK9B+0EIacqTO6hOxh9NDAe+iBun/2/UDHaTVpulJ2vF5D8dZsIRMOcG+jYiqOWA3IceXZuW+0wXocoH3557B5pJUlsJpbHQuV4KjSbLWjXWWthLcTWn5RkREV1H8t3Ghyy306XguAdzOySXqhOJ9x6MBB9up9TNDqkIJyXZIqPFNbCmGX1iiazn+xs0rMnCgJZC+ZAToYg8PH0NyGPkyzIarf0jYLcTKp/xfJHJ/NZOCVJ8CuVy+sAbczm1nMh8+yIJ/orq9xAJOrsm5xsiOsrL9wnJd5D8cSUwqpgkmd99u1L89w4N0XHsGFdI1tkWf3mTcWXu1p7PmDA4j0cF++nFWojF6BiZziYlXjLoyywy/OO08Kk0kB6Z1wjHVVWNQXaThKkZ3E8yMaLfIleysBMg7VBQicdM5+UvYoAjWNm7Xmt+DKN/Gu5Qzw98W+1LOh6gS1ME1JHS9o23EMSLCQU3F0IGOLOaVAl+3QL3v6ZVw8Iv48IvOda5Y8phMiX7Zmtb1Ujnq+FIpsO2wn6dblEx0z+coO6M2KnICOOSrtq3ErEDglsEVOmIe1ASmW/mblie1quI/5CBrgihVhY08UEPnAeJWFCZ6pLWkVnl3kFvIe0HLekBT/jOQ/0mS6NoSy/GARSDNuD8/0LzuMYZSQiTv7NY+CUp4slSwRpjvrV2s8yc9Ra2Gb+ZAXutoY97JDXmADgwuQFJqwM7g4NkKliD8yNXlrbYumgi4u6TaZj6paAmNepbf3r+mFc+m2bxD2so/zqJA3Jbzna/9b3k7XA0bDg6gVum6fIcen1qVnysPAvOhLhoED9hvbO4U11HYdtwu7TIdMN0SZJqCpo5+HFBrXhctlUa55Axm7vVLyOphmfVY/hkkbGLf7b+WMvkjTmYmmwt0+0WKztLLHcIXZyKmmqTZeQm0U08PXmJPdJJLvTChrfHdd9s0DtmPWRgJCtRVreCd+ALeHkBHHplHiABUyyFNvhI38woLQJvfjUPzB1DqO9lAbddwZxCpJN+25eOccTIYSgXdLYENDVFGMNsucsCnONi2pqBUWghOGlANWASHLQoTeFnEJoJJA1pVfC+FTxSbV/auOEX1s/ZpjnhSfPUdAe/dJaOSo78vdsiCYJpjKr07Bq9wmX+CO0/5seINqozGygugKI/0n/e9QKIyIh31CdAZdXrL5a3jlu2vsgxy053IITEtoGNsOkmhETZSfi5j3hCLb5L5cLCVgN2INxrWyzc7w84meEqfKJDPvlGcY+fAsRxT/VteLH0EA9CUMMX3fhZC8mO07hKA5Ny7e0xE0ITB2B4oUSLvRbsidDEXSZY6k9ESJV4zcRxlywP1uU4o/9G5yzYEGtiBrub7hSizu66VhNfAMnlfwY2PeopRJg7JqPilmCjWs6Lv3c/ZRipDDKAd5bpePKCXvOkCz/zuvjqVzFxbbyu+jhKo4qGpoJHU6+l+wnwQwsbvUa9BLyrJGFHP/uRluZqw8PCpokcW98rcGB7Yw60v+G+OLcZBsA76952nhlaxh21G2ERb2m2HapiR9y0Ao5EKCgwQj2Z+rsCVuSOs8gceBK66Ctq+82kiA5pXZVbS3mhOKSkAQ1XbQGUiuFTNwyWTQvjAQyZ8/dgs56o5GEWW+4xvq0MQbKVhCfpSJdFlANP4mdrTadSb3iFK5esQeOKYF6tpidZC7C0rfgsr1LzavsWRYmKcva44hCHPVEo3PNjaaCfITG6Ob/xbuk2oDSTkG/KI8CKnCsRU4c2kQMZfsh5hfZZBQ8jZUJRlFqmMixBPKdfoRjVhINWRgPw9FOhFuDKtbg+E3zybPzjOAkttqFly/rVvBSzFRXHtEMCMQVinbqYa+vOmNKFJ9K7ojD2vQEmSdpHbKc7ZEzCXqY/6hqtq+4be3bKqQeHWkIQdkGJPgv43iRRUjU2yRchDXj8YCJRPs3WoMIa96HnTdi/2eC2EUaGC/6v274kqmPlm3QmD6TG2r6mDbMZBAKafqsN+cZikyw4gufq0WRFmE06DLHGPJKe0h7tlDunWuqssh+LvfTlT/fI2v6o+LjuVopXsuRNmAOY8LeBW5QWzg87PTORK850OF9K5q+qnr4cWR/sjCg65+4POL4hrOp2TvjphsBxBn0VyWt2+ijSlUlWCxF9BUUTRqZB1t9jMjZi6eVC1WppUqTTf+QAIOQAV8Gxwb/hSpnbk/0Ml2GZRvC8A2WWvcCeQYXdKnw8KMeGaMJHbO6A1XJv1O4wKMGuySfODhiZ0CiMSTe+IwDUrhzLuVEfpfYuGb7Z3Hzi38TS1q+8Hm+3aUlUHKTQd8Ic7C94/NneKFbTTwtDSwaZVO1jlMTkvfOSw6BXVZtpR8Ff280d+Bzs1TGhCP0DxJkboq2THS+WfLdBNoCXV9XEVHj5fmBZTgP9wu8dUatyBUD7GK+lCBn7+WnJNbqjLFaqeCdEeUxV/YgD8K1WDLU5LozeuQYVEdrZ350/ayPGpTDR0bfLIPCq+Cy8uNyXATmjx/GdvWXSNEcYt/9tvSiWwP3dx4eEql1/olWtsWISKrqREQ5wXvxh+F/UgQ1PjoJY4vorEEp4pgVq1HfVpewR8KiStJEblff6/OFsgWohvjIajlarO/ubctRfqbXm7dslN4SIoyiszpLZHJOFjwecUZgI3jVUrFniW8yW6zSI4xUfGOsdjhUiNGCk4H19agtL3h90tHS2WpCiE8cDC63TNkRzNUY4Ho46su/hxBdrK1bjerueU15Jmkiix/yYxddONGi0wtfofjA+YsfD4Kt9SnXIOCjGnRSLWDmAl0kdHY2cTmV+mZToWyL1ZHZJYRMVM1vK0Y9eh6DVlD+wQ=";
/** Add tools decrypted from DEV_SEALED to the lists every page reads. */
export function addTools(list) {
  for (const t of list) if (!ALL_TOOLS.some(x => x.slug === t.slug)) { ALL_TOOLS.push(t); if (onSite(t)) TOOLS.push(forSite(t)); }
}
export const inCat = (t, id) => t.cats.includes(id);
const rank = c => (ORDER[SITE] ? ORDER[SITE].indexOf(c.id) : -1);
// Only categories with a tool on this site; the deterrence site uses its own order.
export const CATEGORIES = ALL_CATEGORIES.filter(c => onSite(c) && !c.hidden && ((c.sealed && DEV_SEALED) || TOOLS.some(t => inCat(t, c.id))))
  .sort((a, b) => (ORDER[SITE] ? rank(a) - rank(b) : 0));
