// Every TSM interactive, grouped for the landing page. status: 'live' | 'soon'.
// Each tool lives at tools/<slug>/ with index.html and thumb.svg.
// sites: which published sites show an entry ('tsm' = Interactive Deterrence, 'deterrence' = Interactive Deterrence).
// Entries without `sites` appear on both. The build writes the site id into site.js.
import { SITE } from './site.js';

export const ALL_CATEGORIES = [
  { id: 'trackers', name: 'Live trackers', blurb: 'Taiwan Strait tracker data you can filter, scrub and explore.' },
  { id: 'crisis', name: 'Crises & exercises', blurb: 'How PLA pressure campaigns unfold, and how to read the warning signs.' },
  { id: 'geo', name: 'Indo-Pacific geography', blurb: 'Island chains, chokepoints, contested features and the cables beneath them.' },
  { id: 'models', name: 'Force & wargame models', blurb: 'Hands-on models of kill chains, blockades, mines and defense budgets.' },
  { id: 'narrative', name: 'Narrative & rhetoric', blurb: 'What Beijing says, how it spreads, and what markets and analysts expect.' },
  { id: 'classroom', name: 'Classroom', blurb: 'Teaching tools for courses on deterrence, strategy and cross-Strait history.' },
  { id: 'public', name: 'Public explainers', blurb: 'Short, shareable pieces for a general audience.' },
  { id: 'deterrence', name: 'Deterrence & signaling', sites: ['deterrence'],
    blurb: 'Threats, promises and signals as formal models and history, from conventional to extended nuclear deterrence.' },
  { id: 'gametheory', name: 'Game theory', sites: ['deterrence'],
    blurb: 'Every tool built on a game-theory model: bargaining, signaling, brinkmanship, deterrence, inspection and cascades.' },
  { id: 'nuclear', name: 'Nuclear weapons & arms control', sites: ['deterrence'],
    blurb: 'Arsenals, treaties and escalation, country by country and crisis by crisis.' },
  { id: 'ukraine', name: 'Russia & Ukraine', sites: ['deterrence'],
    blurb: 'The war in data: strikes, air defense, nuclear signaling and support.' },
  { id: 'mideast', name: 'Middle East', sites: ['deterrence'],
    blurb: 'Chokepoints, shipping and missile exchanges from the Red Sea to Hormuz.' },
  { id: 'infowar', name: 'Disinformation & cognitive warfare', sites: ['deterrence'],
    blurb: 'How false stories spread and stick, and how belief updating can be attacked.' },
  { id: 'rhetoric', name: 'State rhetoric', sites: ['deterrence'],
    blurb: 'What governments say, week by week: China, Russia and others, phrase by phrase.' },
  { id: 'coercion', name: 'Economic coercion & war markets', sites: ['deterrence'],
    blurb: 'Trade pressure, resilience, and what betting markets say about war.' },
  { id: 'tsm', name: 'TSM', sites: ['deterrence'], locked: true,
    blurb: 'Taiwan Strait trackers, exercise replays and wargames from the Taiwan Security Monitor. Password protected.' },
];

export const ALL_TOOLS = [
  { slug: 'strait-layers', siteCat: { deterrence: 'tsm' }, cat: 'models', title: 'Strait Layers', status: 'live',
    blurb: 'PLA A2/AD rings, the kill chain behind them, a PLA crossing, and salvo math.' },
  { slug: 'ccg-grayzone', sites: ['tsm'], cat: 'trackers', title: 'CCG Gray-Zone Map', status: 'live',
    blurb: 'Every China Coast Guard incident the Taiwan Security Monitor has recorded since June 2024, on a map with a year selector and time slider.' },
  { slug: 'transit-response', siteCat: { deterrence: 'tsm' }, cat: 'trackers', title: 'Transit Response Explorer', status: 'live',
    blurb: 'Pick an allied Strait transit and see how the PLA answered in the days around it.' },
  { slug: 'strait-snapshot', sites: ['tsm'], cat: 'trackers', title: 'Strait Snapshot Live', status: 'live',
    blurb: 'The six monthly Strait Snapshot figures as live charts for any month of 2026.' },
  { slug: 'arms-backlog', sites: ['tsm'], cat: 'trackers', title: 'Arms Sales Backlog', status: 'live',
    blurb: 'Every U.S. arms sale Taiwan is still waiting for, from notification to delivery, with the backlog total over time.' },
  { slug: 'dark-fleet', sites: ['tsm'], cat: 'trackers', title: 'Dark Fleet Viewer', status: 'live',
    blurb: 'Chinese-flag AIS tracks around Taiwan from the Taiwan Security Monitor\'s AIS database, when they go dark, and two years of coast guard and militia activity.' },
  { slug: 'flight-atlas', sites: ['tsm'], cat: 'trackers', title: 'PLA Flight-Path Atlas', status: 'live',
    blurb: "Which sectors of Taiwan's ADIZ PLA aircraft entered, day by day since 2020, read from the text of MND's daily reports." },
  { slug: 'balloon-tracker', sites: ['tsm'], cat: 'trackers', title: 'Balloon Tracker', status: 'live',
    blurb: "PRC balloons reported by Taiwan's MND: where MND placed them, when they came, and how they cluster in winter." },
  { slug: 'kinmen-closeup', sites: ['tsm'], cat: 'trackers', title: 'Kinmen Close-Up', status: 'live',
    blurb: "China Coast Guard incursions at Kinmen, 2024\u201326, mapped inside Taiwan's officially published boundary, with the hulls that keep coming back." },
  { slug: 'joint-sword', siteCat: { deterrence: 'tsm' }, cat: 'crisis', title: 'Anatomy of an Exercise', status: 'live',
    blurb: 'Major PLA exercises around Taiwan, replayed day by day with published zones, daily counts and statements.' },
  { slug: 'escalation-ladder', sites: ['tsm'], cat: 'crisis', title: 'Escalation Ladder', status: 'live',
    blurb: 'A hypothetical Kinmen quarantine crisis: choose Taipei, Washington and Tokyo moves and watch the rungs light up.' },
  { slug: 'coercion-options', sites: ['tsm'], cat: 'crisis', title: 'Quarantine, Blockade, Invasion', status: 'live',
    blurb: 'Five coercive options side by side, from gray zone to invasion: legal status, warning, costs and triggers.' },
  { slug: 'warning-board', siteCat: { deterrence: 'tsm' }, cat: 'crisis', title: 'Indicators & Warning Board', status: 'live',
    blurb: 'Exercises light up the board too. Set 33 sourced indicators and see what separates a drill from preparation for war.' },
  { slug: 'island-chains', sites: ['tsm'], cat: 'geo', title: 'Island Chains & Access', status: 'live',
    blurb: 'First and second island chains, U.S. and allied basing, and what can reach what.' },
  { slug: 'chokepoints', sites: ['tsm'], cat: 'geo', title: 'Chokepoint Dashboard', status: 'live',
    blurb: 'Close Malacca, Luzon or the Taiwan Strait and watch the tanker reroute, with the added days and cost.' },
  { slug: 'scs-features', sites: ['tsm'], cat: 'geo', title: 'South China Sea Features', status: 'live',
    blurb: 'Who holds which reef, what China built, and what the 2016 tribunal ruled.' },
  { slug: 'undersea-cables', sites: ['tsm'], cat: 'geo', title: 'Taiwan\'s Undersea Cables', status: 'live',
    blurb: 'Where Taiwan\'s submarine cables land, and which islands go dark when you cut them.' },
  { slug: 'japan-view', sites: ['tsm'], cat: 'geo', title: "Japan's View: PLA Near Japan", status: 'live',
    blurb: "Every PLA Navy crossing of Japan's straits that Tokyo reported in 2025\u201326, by strait, direction and hull number, set against Taiwan's daily counts." },
  { slug: 'crossing-windows', siteCat: { deterrence: 'tsm' }, cat: 'geo', title: 'Crossing Windows', status: 'live',
    blurb: 'Thirty years of Taiwan Strait wind, wave, fog and typhoon records, tested against sea-state limits you set: which weeks allowed an amphibious crossing, and how the claimed April and October windows hold up.' },
  { slug: 'energy-blockade', sites: ['tsm'], cat: 'models', title: 'Energy Blockade Clock', status: 'live',
    blurb: 'Set a quarantine or blockade and watch Taiwan\'s LNG, coal and oil stocks run down, and who loses power first.' },
  { slug: 'budget-allocator', cat: 'models', title: 'Defense Budget Allocator', status: 'live',
    blurb: "Spend Taiwan's NT$145.7bn supplementary defense line, or Japan's, the Philippines' or Poland's real defense budgets, and test the mix against a notional model of an attack on each." },
  { slug: 'mine-warfare', sites: ['tsm'], cat: 'models', title: 'Mine Warfare Simulator', status: 'live',
    blurb: 'Lay a minefield off a generic beach, choose how the PLA clears it, and see what mines do to a landing\'s timing and cost.' },
  { slug: 'kill-chain-builder', cat: 'models', title: 'Kill Chain Builder', status: 'live',
    blurb: 'Wire sensors, command nodes and shooters into a kill chain, race the clock against a moving target, then strike nodes to find where it breaks.' },
  { slug: 'penghu-gambit', siteCat: { deterrence: 'tsm' }, cat: 'models', title: 'Penghu Gambit', status: 'live',
    blurb: "Set Taiwan's defenses and the PLA's plan, play out a notional seizure of Penghu in 12-hour turns with every die roll shown, then run 1,000 games to see what drives the outcome." },
  { slug: 'interceptor-burndown', cat: 'models', title: 'Interceptor Burn-down', status: 'live',
    blurb: "Set a daily PRC missile and drone salvo against open-source estimates of Taiwan's Patriot and Tien Kung stocks and see the day each runs dry, how many threats get through, and which assumption matters most." },
  { slug: 'wargame-explorer', siteCat: { deterrence: 'tsm' }, cat: 'models', title: 'Wargame Results Explorer', status: 'live',
    blurb: 'Eight published Taiwan wargames side by side: what each assumed, how it came out, and which assumptions (above all Japan basing and U.S. entry) drive the result, with a page citation for every figure.' },
  { slug: 'rhetoric-heatmap', siteCat: { deterrence: 'rhetoric' }, cat: 'narrative', title: 'PRC Rhetoric Heatmap', status: 'live',
    blurb: 'Foreign Ministry, Defense Ministry and Taiwan Affairs Office language, week by week.' },
  { slug: 'beijing-decoder', sites: ['tsm'], cat: 'narrative', title: 'Beijing Decoder', status: 'live',
    blurb: 'Paste a PRC statement and see what each formula has signalled before.' },
  { slug: 'narrative-diffusion', sites: ['tsm'], cat: 'narrative', title: 'Narrative Diffusion', status: 'live',
    blurb: 'Follow one PRC talking point from the podium through state media, with the data gaps shown.' },
  { slug: 'markets-vs-analysts', sites: ['tsm'], cat: 'narrative', title: 'Markets vs. Analysts', status: 'live',
    blurb: 'What traders pay for a Chinese invasion, blockade or clash, against the PLA activity record.' },
  { slug: 'deterrence-lab', sites: ['tsm'], cat: 'classroom', title: 'Deterrence Lab', status: 'live',
    blurb: 'Audience costs, costly signals and salami tactics as formal models: move the costs and beliefs and watch the equilibrium shift.' },
  { slug: 'history-time-machine', sites: ['tsm'], cat: 'classroom', title: 'Taiwan Time Machine', status: 'live',
    blurb: 'Scrub from 1895 to today: who controlled Taiwan, Penghu, Kinmen, Matsu and the Dachens, and the treaties, crises and U.S. documents behind each change.' },
  { slug: 'orbat-cards', sites: ['tsm'], cat: 'classroom', title: 'Order of Battle Cards', status: 'live',
    blurb: 'Flip cards for PLA, Taiwanese, Japanese, Philippine and U.S. formations around Taiwan, placed by HQ city, with a student quiz.' },
  { slug: 'packet-builder', sites: ['tsm'], cat: 'classroom', title: 'Briefing Packet Builder', status: 'live',
    blurb: 'Pick a date range and get a printable Taiwan Strait briefing packet: PLA activity against the prior period, coast guard incidents, transits, exercises, PRC statements and every source.' },
  { slug: 'day-in-the-strait', sites: ['tsm'], cat: 'public', title: 'A Day in the Strait', status: 'live',
    blurb: 'One real day of gray-zone pressure around Taiwan, built from the data. Pick any day of 2026.' },
  { slug: 'how-close', sites: ['tsm'], cat: 'public', title: 'How Close Is China?', status: 'live',
    blurb: 'Type a city and see how far it is from Taiwan and from China, with the Taiwan Strait for scale.' },
  { slug: 'conceal-reveal', also: ['gametheory'], cat: 'deterrence', sites: ['deterrence'], title: 'Conceal or Reveal?', status: 'live',
    blurb: "Why do states with similar weapons make opposite choices about showing them? Move the costs and beliefs in Walberg's signaling model and watch coercive states reveal while operational states conceal." },
  { slug: 'extended-deterrence', also: ['gametheory'], cat: 'deterrence', sites: ['deterrence'], title: 'Extended Deterrence', status: 'live',
    blurb: 'Would a patron trade Boston for Bonn? Stack treaties, pledges, a tripwire force and nuclear sharing, see what each does to credibility and entrapment, then check the real U.S. commitments.' },
  { slug: 'nuclear-arsenals', cat: 'nuclear', sites: ['deterrence'], title: 'Nuclear Arsenals', status: 'live',
    blurb: "Scrub eighty years of FAS nuclear warhead estimates for every nuclear-armed state, against the treaties from the NPT to New START's lapse in February 2026." },
  { slug: 'escalation-ladder-kahn', cat: 'nuclear', sites: ['deterrence'], title: "Kahn's Escalation Ladder", status: 'live',
    blurb: "Step through nuclear crises from Cuba 1962 to Russia 2022 and India–Pakistan 2025 on Herman Kahn's 44-rung ladder, compare them, and read why the ladder misleads." },
  { slug: 'deterrence-lab-general', also: ['gametheory'], cat: 'deterrence', sites: ['deterrence'], title: 'Deterrence Lab', status: 'live',
    blurb: 'Move the costs and beliefs in three classic deterrence models (audience costs, costly signals and salami tactics) and test them against sourced crises from Fashoda in 1898 to Crimea in 2014.' },
  { slug: 'misinfo-cascade', also: ['gametheory'], cat: 'infowar', sites: ['deterrence'], locked: true, title: 'Misinformation Cascade', status: 'live',
    blurb: "Watch a report of 16 aircraft become 'the island is surrounded' as it spreads, and test when a correction can still stop it." },
  { slug: 'bayesian-attack', also: ['gametheory'], cat: 'infowar', sites: ['deterrence'], title: 'Attacking the Update', status: 'live',
    blurb: "An adversary doesn't fake the evidence; it changes how much you weigh it. Watch true signals produce a false conclusion, and see which defenses still work." },
  { slug: 'ukraine-air-war', cat: 'ukraine', sites: ['deterrence'], title: "Ukraine's Air War", status: 'live',
    blurb: 'Russian missile and drone launches against Ukraine since 2022, by weapon type, with the share the Ukrainian Air Force reported shooting down.' },
  { slug: 'russia-nuclear-signals', cat: 'ukraine', sites: ['deterrence'], title: "Russia's Nuclear Signals", status: 'live',
    blurb: 'Every major Russian nuclear signal since February 2022, sourced and scored by what it changed, set against Western responses and the course of the war.' },
  { slug: 'red-sea-hormuz', cat: 'mideast', sites: ['deterrence'], title: 'Red Sea & Hormuz Pulse', status: 'live',
    blurb: 'Daily ship counts through Bab el-Mandeb, Suez and Hormuz from IMF PortWatch, against a sourced timeline of Houthi attacks, strikes, pauses and the 2026 Hormuz mining.' },
  { slug: 'iran-israel-salvos', cat: 'mideast', sites: ['deterrence'], title: 'Iran–Israel Salvos', status: 'live',
    blurb: "Iran's three direct attacks on Israel side by side: what was launched, what was stopped, who defended with what, and what it cost, with every figure sourced and every disagreement shown." },
  { slug: 'coercion-resilience', cat: 'coercion', sites: ['deterrence'], title: 'Coercion Without Concession', status: 'live',
    blurb: "China's trade punishment of Australia and South Korea in real trade and tourism data: what was hit, what found other buyers, and what Beijing failed to change." },
  { slug: 'war-markets', cat: 'coercion', sites: ['deterrence'], title: 'War Markets', status: 'live',
    blurb: 'What prediction markets priced for strikes on Iran, ceasefires and a Russia–NATO clash in 2026, set against how each contract resolved.' },
  { slug: 'crisis-stability', cat: 'nuclear', sites: ['deterrence'], title: 'Crisis Stability Calculator', status: 'live',
    blurb: "Set two notional force postures and see Kent and Thaler's first-strike stability index: who gains by striking first, and how MIRVed silos, alert rates and launch under attack move it." },
  { slug: 'verification-game', also: ['gametheory'], cat: 'nuclear', sites: ['deterrence'], title: 'Trust but Verify', status: 'live',
    blurb: 'An arms-control inspection game from the published literature: how inspection quotas, detection, false-alarm costs and penalties set the odds of cheating and of getting caught, beside New START, IAEA and CTBT verification.' },
  { slug: 'entanglement', cat: 'nuclear', sites: ['deterrence'], title: 'Nuclear Entanglement', status: 'live',
    blurb: 'Plan a conventional campaign against satellites, command links, launchers and bases that also serve nuclear forces, and watch use-or-lose pressure, misread warning and the fog of war push a notional escalation risk up, then test the fixes the literature proposes.' },
  { slug: 'warhead-ambiguity', cat: 'nuclear', sites: ['deterrence'], title: 'Is It a Nuke?', status: 'live',
    blurb: 'Your sensors report an incoming missile that could carry either warhead: update on context, launch site and trajectory, then wait, hit back conventionally or launch on warning, and see how priors and entanglement produce false alarms.' },
  { slug: 'nuclear-tests', cat: 'nuclear', sites: ['deterrence'], title: 'Every Nuclear Test', status: 'live',
    blurb: 'Scrub through all 2,056 nuclear tests since Trinity by state, environment, yield and test site, reconciled against the ACA, SIPRI and DOE counts and the treaties that drove testing underground and then stopped it.' },
  { slug: 'declaratory-policy', cat: 'nuclear', sites: ['deterrence'], title: 'Who Promises What', status: 'live',
    blurb: "No-first-use pledges, assurances, red lines and alert postures for all nine nuclear-armed states, quoted from their own documents and dated, with 'not declared' where a state has said nothing." },
  { slug: 'game-theory-gallery', cat: 'gametheory', also: ['deterrence'], sites: ['deterrence'], title: 'Game Theory Gallery', status: 'live',
    blurb: "Move the costs, beliefs and balance of power in eight classic game-theory models of war and cooperation, from Fearon's bargaining range to Schelling's brinkmanship, and watch the equilibrium change, with every result cited to the page." },
  { slug: 'ukraine-support', cat: 'ukraine', sites: ['deterrence'], title: 'Who Supports Ukraine', status: 'live',
    blurb: 'Who pledged aid to Ukraine and who delivered it: military, financial and humanitarian support by donor since 2022, in euros or as a share of GDP, from the Kiel Institute.' },
  { slug: 'prebunking-game', cat: 'infowar', sites: ['deterrence'], title: 'Prebunking Game', status: 'live',
    blurb: 'Learn six manipulation techniques on invented posts, then see whether you tell manipulative posts from plain ones better, next to what the published Bad News studies found.' },
  { slug: 'sanctions-explorer', cat: 'coercion', sites: ['deterrence'], title: 'Sanctions Explorer', status: 'live',
    blurb: 'Sixty years of sanctions threats and impositions from the TIES dataset: filter by sender, target, objective and type, see how often the target gave in, and set that beside what the Global Sanctions Data Base authors report.' },
  { slug: 'cost-ratio', cat: 'gametheory', sites: ['deterrence'], title: 'Cost Ratio Bargaining', status: 'live',
    blurb: 'Hold the total cost of war fixed, shift who pays it, and watch the peaceful settlement move toward the side whose cost of fighting fell.' },
  { slug: 'humiliation-motivation', cat: 'deterrence', also: ['gametheory'], sites: ['deterrence'], title: 'Humiliation to Motivation', status: 'live',
    blurb: 'Past a severity threshold even weak states challenge the order that humiliated them, and a challenge stops telling the dominant power anything.' },
  { slug: 'proliferation-paths', cat: 'nuclear', sites: ['deterrence'], title: 'Proliferation Paths', status: 'live',
    blurb: 'Scrub from 1939 to 2017 to watch states explore, pursue, acquire and give up nuclear weapons, as three published datasets code it, with every disagreement between them shown.' },
  { slug: 'treaty-tracker', cat: 'nuclear', sites: ['deterrence'], title: 'Treaty Tracker', status: 'live',
    blurb: 'Twenty nuclear and arms-control treaties, 197 states, 1963 to 2026: scrub the years to see who signed, joined, suspended or walked away, with every date traced to a depositary record or official statement.' },
  { slug: 'sea-control', cat: 'gametheory', also: ['models'], sites: ['deterrence'], title: 'Sea Control Game', status: 'live',
    blurb: "Split a navy's budget between a Mahanian battle fleet and Corbettian distributed forces, and see whether the challenger fights, waits or denies." },
  { slug: 'arms-race', cat: 'gametheory', also: ['nuclear'], sites: ['deterrence'], title: 'Arms Race Dynamics', status: 'live',
    blurb: "Richardson's arms-race equations as a phase plane you can click: set reaction, fatigue and grievance, and see which races settle, which run away, and what happens with a third rival." },
];

export const onSite = (x, site = SITE) => !x.sites || x.sites.includes(site);
/** A tool's category on a given site (siteCat overrides cat per site). */
export const catOn = (t, site = SITE) => (t.siteCat && t.siteCat[site]) || t.cat;
const ORDER = { deterrence: ['deterrence', 'gametheory', 'nuclear', 'ukraine', 'mideast', 'infowar', 'rhetoric', 'coercion', 'models', 'tsm'] };
// `also` lists extra categories a tool appears in; `cats` is its primary category plus those.
export const TOOLS = ALL_TOOLS.filter(t => onSite(t)).map(t => ({ ...t, cat: catOn(t), cats: [catOn(t), ...(t.also || [])] }));
export const inCat = (t, id) => t.cats.includes(id);
const rank = c => (ORDER[SITE] ? ORDER[SITE].indexOf(c.id) : -1);
// Only categories with a tool on this site; the deterrence site uses its own order.
export const CATEGORIES = ALL_CATEGORIES.filter(c => onSite(c) && TOOLS.some(t => inCat(t, c.id)))
  .sort((a, b) => (ORDER[SITE] ? rank(a) - rank(b) : 0));
