// Every TSM interactive, grouped for the landing page. status: 'live' | 'soon'.
// Each tool lives at tools/<slug>/ with index.html and thumb.svg.
// sites: which published sites show an entry ('tsm' = Interactive Deterrence, 'deterrence' = Interactive Deterrence,
// 'narratives' = Narrative Tracking at jwalberg.com/narratives/).
// Entries without `sites` appear on tsm and deterrence. The build writes the site id into site.js.
import { SITE } from './site.js';

const CATEGORY_LIST = [
  { id: 'trackers', name: 'Live trackers', blurb: 'Taiwan Strait tracker data you can filter and explore.' },
  { id: 'crisis', name: 'Crises & exercises', blurb: 'How PLA pressure campaigns unfold, and how to read the warning signs.' },
  { id: 'geo', name: 'Indo-Pacific geography', blurb: 'Island chains, chokepoints, contested features and the cables beneath them.' },
  { id: 'models', name: 'Force & wargame models', siteName: { deterrence: 'War Games and Simulations' },
    siteBlurb: { deterrence: 'Wargames to play, from Kharg Island to the trenches, and models of kill chains and budgets.' },
    blurb: 'Hands-on models of kill chains, blockades, mines and defense budgets.',
    subs: [{ id: 'wargames', name: 'Wargames', blurb: 'Play a side: raids, island assaults, submarine hunts, trench defense and matrix games.' },
      { id: 'budget', name: 'Budget and Logistics', blurb: 'Budgets, kill chains, interceptor stocks and mine clearance.' }] },
  { id: 'narrative', name: 'Narrative & rhetoric', blurb: 'What Beijing says and how it spreads through state media.' },
  { id: 'classroom', name: 'Classroom', blurb: 'Teaching tools for courses on deterrence, strategy and cross-Strait history.' },
  { id: 'public', name: 'Public explainers', blurb: 'Short, shareable pieces for a general audience.' },
  { id: 'gametheory', name: 'Game theory', sites: ['deterrence'],
    blurb: 'Game-theory models of bargaining, signaling, brinkmanship, deterrence and inspection, and the markets that price war.' },
  { id: 'nuclear', name: 'Nuclear weapons & arms control', sites: ['deterrence'],
    blurb: 'Arsenals, treaties and escalation, country by country and crisis by crisis.',
    // Subsections: tools pick one with `sub: { nuclear: '<id>' }`.
    subs: [{ id: 'facts', name: 'Fact Sheets', blurb: 'Sourced data you can browse: arsenals, tests, doctrine, treaties and proliferation.' },
      { id: 'playground', name: 'Models / Nuclear Playground', blurb: 'Models to play with: warhead ambiguity, entanglement, crisis stability and escalation.' }] },
  { id: 'regions', name: 'Regions', sites: ['deterrence'],
    blurb: 'Wars and flashpoints by region: Russia and Ukraine, the Middle East and the Indo-Pacific.',
    subs: [{ id: 'ukraine', name: 'Russia & Ukraine', blurb: 'The war in data: strikes, air defense, nuclear signaling and support.' },
      { id: 'mideast', name: 'Middle East', blurb: 'Chokepoints, shipping and missile exchanges from the Red Sea to Hormuz.' },
      { id: 'indopacific', name: 'Indo-Pacific', locked: true, blurb: 'Taiwan Strait trackers, exercise replays and wargames.' }] },
  { id: 'narratives', name: 'Disinfo and Narratives', sites: ['deterrence'],
    blurb: 'How false stories spread and stick, and what governments say, phrase by phrase.',
    subs: [{ id: 'disinfo', name: 'Disinformation & cognitive warfare', blurb: 'How false stories spread and stick, and how belief updating can be attacked.' },
      { id: 'rhetoric', name: 'State rhetoric', blurb: 'What governments say, week by week: China, Russia and others, phrase by phrase.' }] },
  // jwalberg.com/narratives/: public rhetoric trackers (Rhetoric Search keeps its own password). Landing page lives in jowal6.
  { id: 'tracking', name: 'Narrative Tracking', sites: ['narratives'],
    blurb: 'What governments say, week by week, and every mention searchable.' },
  // Taiwan tools behind the second password. Hidden as a top-level section; shown as Regions › Indo-Pacific.
  { id: 'tsm', name: 'Indo-Pacific', sites: ['deterrence'], locked: true, hidden: true,
    blurb: 'Taiwan Strait trackers, exercise replays and wargames.' },
  // Tools marked `dev: true` show only here (never in their other categories) and need their own password.
  // `sealed`: on the published site their registry entries are encrypted (DEV_SEALED below), so the section
  // itself asks for the password before it lists anything.
  { id: 'dev', name: 'Coming Soon', sites: ['deterrence'], locked: true, sealed: true,
    blurb: 'Tools still being built and checked.',
    subs: [{ id: 'games', name: 'Coming Soon games', blurb: 'New games to play-test before they go public.' },
      { id: 'safeguards', name: 'Weapons policy and enforcement', blurb: 'Enforcement, threat-intel and arms-law tools to check before they go public.' }] },
];
// siteName and siteBlurb rename or re-describe a section on one site only.
export const ALL_CATEGORIES = CATEGORY_LIST.map(c => ({ ...c, name: (c.siteName && c.siteName[SITE]) || c.name,
  blurb: (c.siteBlurb && c.siteBlurb[SITE]) || c.blurb }));

export const ALL_TOOLS = [
  { slug: 'strait-layers', siteCat: { deterrence: 'tsm' }, also: ['regions'], sub: { regions: 'indopacific' }, cat: 'models', title: 'Strait Layers', status: 'live',
    blurb: 'PLA A2/AD rings, the kill chain behind them, a PLA crossing, and salvo math.' },
  { slug: 'ccg-grayzone', sites: ['tsm'], cat: 'trackers', title: 'CCG Gray-Zone Map', status: 'live',
    blurb: 'Every China Coast Guard incident the Taiwan Security Monitor has recorded since June 2024, on a map with a year selector and time slider.' },
  { slug: 'transit-response', siteCat: { deterrence: 'tsm' }, also: ['regions'], sub: { regions: 'indopacific' }, cat: 'trackers', title: 'Transit Response Explorer', status: 'live',
    blurb: 'Pick an allied Strait transit and see how the PLA answered in the days around it.' },
  { slug: 'strait-snapshot', sites: ['tsm'], cat: 'trackers', title: 'Strait Snapshot Live', status: 'live',
    blurb: 'The six monthly Strait Snapshot figures as live charts for any month of 2026.' },
  { slug: 'arms-backlog', sites: ['tsm'], cat: 'trackers', title: 'Arms Sales Backlog', status: 'live',
    blurb: 'Every U.S. arms sale Taiwan is still waiting for, from notification to delivery, with the backlog total over time.' },
  { slug: 'strait-4d', sites: ['tsm'], cat: 'trackers', title: 'Strait 4D', status: 'live',
    blurb: 'Every day since August 2022 on one tilted 3D map: PLA activity, exercise zones, coast guard and gray-zone ships, cable incidents and what Beijing said, with crisis replays and anomaly flags.' },
  { slug: 'forecast-board', sites: ['tsm'], cat: 'trackers', title: 'Crowd Forecast Board', status: 'live',
    blurb: 'Live Polymarket prices on a Chinese invasion, blockade or clash and other conflicts, scored against what happened, with Walberg\'s test for informed trading by theater.' },
  { slug: 'video-briefings', sites: ['tsm'], cat: 'trackers', title: 'Video Briefings', status: 'live',
    blurb: 'A two-minute narrated video of the week in the Taiwan Strait: PLA air and sea activity, CCG incursions and PRC rhetoric against the previous 12 weeks.' },
  { slug: 'say-do-taiwan', sites: ['tsm'], cat: 'narrative', also: ['trackers'], title: 'Say–Do Gap Monitor', status: 'live',
    blurb: 'Does what Beijing says predict what the PLA and coast guard do around Taiwan? Three tests, corrected for multiple testing, with the evidence for every spike.' },
  { slug: 'dark-fleet', sites: ['tsm'], cat: 'trackers', title: 'Dark Fleet Viewer', status: 'live',
    blurb: 'Chinese-flag AIS tracks around Taiwan from the Taiwan Security Monitor\'s AIS database, when they go dark, and two years of coast guard and militia activity.' },
  { slug: 'flight-atlas', sites: ['tsm'], cat: 'trackers', title: 'PLA Flight-Path Atlas', status: 'live',
    blurb: "Which sectors of Taiwan's ADIZ PLA aircraft entered, day by day since 2020, read from the text of MND's daily reports." },
  { slug: 'balloon-tracker', sites: ['tsm'], cat: 'trackers', title: 'Balloon Tracker', status: 'live',
    blurb: "PRC balloons reported by Taiwan's MND: where MND placed them, when they came, and how they cluster in winter." },
  { slug: 'kinmen-closeup', sites: ['tsm'], cat: 'trackers', title: 'Kinmen Close-Up', status: 'live',
    blurb: "China Coast Guard incursions at Kinmen, 2024\u201326, mapped inside Taiwan's officially published boundary, with the hulls that keep coming back." },
  { slug: 'joint-sword', siteCat: { deterrence: 'tsm' }, also: ['regions'], sub: { regions: 'indopacific' }, cat: 'crisis', title: 'Anatomy of an Exercise', status: 'live',
    blurb: 'Major PLA exercises around Taiwan, replayed day by day with published zones, daily counts and statements.' },
  { slug: 'escalation-ladder', sites: ['tsm'], cat: 'crisis', title: 'Escalation Ladder', status: 'live',
    blurb: 'A hypothetical Kinmen quarantine crisis: choose Taipei, Washington and Tokyo moves and watch the rungs light up.' },
  { slug: 'coercion-options', sites: ['tsm'], cat: 'crisis', title: 'Quarantine, Blockade, Invasion', status: 'live',
    blurb: 'Five coercive options side by side, from gray zone to invasion: legal status, warning, costs and triggers.' },
  { slug: 'warning-board', siteCat: { deterrence: 'tsm' }, also: ['regions'], sub: { regions: 'indopacific' }, cat: 'crisis', title: 'Indicators & Warning Board', status: 'live',
    blurb: 'Exercises light up the board too. Set 33 sourced indicators and see what separates a drill from preparation for war.' },
  { slug: 'island-chains', sites: ['tsm'], cat: 'geo', title: 'Island Chains & Access', status: 'live',
    blurb: 'First and second island chains, U.S. and allied basing, and what can reach what.' },
  { slug: 'chokepoints', sites: ['tsm'], cat: 'geo', title: 'Chokepoint Dashboard', status: 'live',
    blurb: 'Close Malacca, Luzon or the Taiwan Strait and watch the tanker reroute, with the added days and cost.' },
  { slug: 'scs-features', sites: ['tsm'], cat: 'geo', title: 'South China Sea Features', status: 'live',
    blurb: 'Who holds which reef, what China built, and what the 2016 tribunal ruled.' },
  { slug: 'undersea-cables', unlisted: true, sites: ['tsm'], cat: 'geo', title: 'Taiwan\'s Undersea Cables', status: 'live',
    blurb: 'Where Taiwan\'s submarine cables land, and which islands go dark when you cut them.' },
  { slug: 'cable-atlas', sites: ['tsm'], cat: 'geo', title: 'Undersea Cable Atlas', status: 'live',
    blurb: 'Every cable and landing site serving Taiwan, the Ryukyus and the Philippines, a sourced log of cuts, repair-ship capacity, and what survives when you cut them.' },
  { slug: 'japan-view', sites: ['tsm'], cat: 'geo', title: "Japan's View: PLA Near Japan", status: 'live',
    blurb: "Every PLA Navy crossing of Japan's straits that Tokyo reported in 2025\u201326, by strait, direction and hull number, set against Taiwan's daily counts." },
  { slug: 'crossing-windows', siteCat: { deterrence: 'tsm' }, also: ['regions'], sub: { regions: 'indopacific' }, cat: 'geo', title: 'Crossing Windows', status: 'live',
    blurb: 'Thirty years of Taiwan Strait wind, wave, fog and typhoon records, tested against sea-state limits you set: which weeks allowed an amphibious crossing, and how the claimed April and October windows hold up.' },
  { slug: 'energy-blockade', unlisted: true, sites: ['tsm'], cat: 'models', title: 'Energy Blockade Clock', status: 'live',
    blurb: 'Set a quarantine or blockade and watch Taiwan\'s LNG, coal and oil stocks run down, and who loses power first.' },
  { slug: 'blockade-sim', sites: ['tsm'], cat: 'models', title: 'Blockade & Quarantine Simulator', status: 'live',
    blurb: 'Set a PRC coast guard quarantine or naval blockade of Taiwan and follow fuel and power, shipping, war-risk insurance, cable repairs, chip output and exports day by day, then compare scenarios.' },
  { slug: 'budget-allocator', sub: { models: 'budget' }, siteBlurb: { tsm: 'Spend Taiwan\'s NT$145.7bn supplementary defense line, or bigger: see what it buys, how long U.S. sales take to arrive, and a notional model shown only as ranges.' }, cat: 'models', title: 'Defense Budget Allocator', status: 'live',
    blurb: "Spend Taiwan's NT$145.7bn supplementary defense line, or a real defense budget from twelve other Indo-Pacific and European countries, see what each mix buys, and explore a notional model shown only as ranges, never as a prediction." },
  { slug: 'mine-warfare', sites: ['tsm'], cat: 'models', title: 'Mine Warfare Simulator', status: 'live',
    blurb: 'Lay a minefield off a generic beach, choose how the PLA clears it, and see what mines do to a landing\'s timing and cost.' },
  { slug: 'kill-chain-builder', game: true, sub: { models: 'budget' }, cat: 'models', title: 'Kill Chain Builder', status: 'live',
    blurb: 'Wire sensors, command nodes and shooters into a kill chain, race the clock against a moving target, then strike nodes to find where it breaks.' },
  { slug: 'penghu-gambit', game: true, siteCat: { deterrence: 'tsm' }, also: ['regions', 'models'], sub: { regions: 'indopacific', models: 'wargames' }, cat: 'models', title: 'Penghu Gambit', status: 'live',
    blurb: "Set Taiwan's defenses and the PLA's plan, play out a notional seizure of Penghu in 12-hour turns with every die roll shown, then run 1,000 games to see what drives the outcome." },
  { slug: 'interceptor-burndown', game: true, sub: { models: 'budget' }, cat: 'models', title: 'Interceptor Burn-down', status: 'live',
    blurb: "Set a daily PRC missile and drone salvo against open-source estimates of Taiwan's Patriot and Tien Kung stocks and see the day each runs dry, how many threats get through, and which assumption matters most." },
  { slug: 'strait-landing', game: true, siteCat: { deterrence: 'tsm' }, also: ['regions', 'models'], sub: { regions: 'indopacific', models: 'wargames' }, cat: 'models', title: 'Strait Landing', status: 'live',
    blurb: "Plan a PLA landing on Taiwan's west coast: send amphibious ships and civilian ferries through real historical sea states, suppress missiles and mines, and race the counterattack to D+3." },
  { slug: 'four-capitals', game: true, sites: ['deterrence'], also: ['regions', 'models'], sub: { regions: 'indopacific', models: 'wargames' }, cat: 'models', title: 'Four Capitals', status: 'live',
    blurb: 'Play Washington, Taipei, Beijing or Tokyo through a notional eight-month Taiwan crisis: a posture and four moves a month, named formations limited by Lift, fuel, munitions and readiness, hidden resolve on every side, scored against your own priorities.' },
  { slug: 'wargame-explorer', siteCat: { deterrence: 'tsm' }, also: ['regions'], sub: { regions: 'indopacific' }, cat: 'models', title: 'Wargame Results Explorer', status: 'live',
    blurb: 'Eight published Taiwan wargames side by side: what each assumed, how it came out, and which assumptions (above all Japan basing and U.S. entry) drive the result, with a page citation for every figure.' },
  { slug: 'rhetoric-heatmap', siteCat: { narratives: 'tracking' }, cat: 'narrative', sites: ['tsm', 'narratives'], title: 'PRC Rhetoric Heatmap', status: 'live',
    blurb: 'Foreign Ministry, Defense Ministry and Taiwan Affairs Office language, week by week.' },
  { slug: 'beijing-decoder', sites: ['tsm'], cat: 'narrative', title: 'Beijing Decoder', status: 'live',
    blurb: 'Paste a PRC statement and see what each formula has signalled before.' },
  { slug: 'narrative-diffusion', sites: ['tsm'], cat: 'narrative', title: 'Narrative Diffusion', status: 'live',
    blurb: 'Follow one PRC talking point from the podium through state media, with the data gaps shown.' },
  { slug: 'deterrence-lab', sites: ['tsm'], cat: 'classroom', title: 'Deterrence Lab', status: 'live',
    blurb: 'Audience costs, costly signals and salami tactics as formal models: move the costs and beliefs and watch the equilibrium shift.' },
  { slug: 'history-time-machine', sites: ['tsm'], cat: 'classroom', title: 'Taiwan Time Machine', status: 'live',
    blurb: 'Explore 1895 to today: who controlled Taiwan, Penghu, Kinmen, Matsu and the Dachens, and the treaties, crises and U.S. documents behind each change.' },
  { slug: 'orbat-cards', sites: ['tsm'], cat: 'classroom', title: 'Order of Battle Cards', status: 'live',
    blurb: 'Flip cards for PLA, Taiwanese, Japanese, Philippine and U.S. formations around Taiwan, placed by HQ city, with a student quiz.' },
  { slug: 'packet-builder', sites: ['tsm'], cat: 'classroom', title: 'Briefing Packet Builder', status: 'live',
    blurb: 'Pick a date range and get a printable Taiwan Strait briefing packet: PLA activity against the prior period, coast guard incidents, transits, exercises, PRC statements and every source.' },
  { slug: 'day-in-the-strait', sites: ['tsm'], cat: 'public', title: 'A Day in the Strait', status: 'live',
    blurb: 'One real day of gray-zone pressure around Taiwan, built from the data. Pick any day of 2026.' },
  { slug: 'how-close', sites: ['tsm'], cat: 'public', title: 'How Close Is China?', status: 'live',
    blurb: 'Type a city and see how far it is from Taiwan and from China, with the Taiwan Strait for scale.' },
  { slug: 'dissertation-games', cat: 'gametheory', sites: ['deterrence'], vault: 'dissertation', title: 'Jon Dissertation Games', status: 'live',
    blurb: "Working game trees from Jonathan Walberg's dissertation." },
  { slug: 'nuclear-arsenals', sub: { nuclear: 'facts' }, cat: 'nuclear', sites: ['deterrence'], title: 'Nuclear Arsenals', status: 'live',
    blurb: "Explore eighty years of FAS nuclear warhead estimates for every nuclear-armed state, against the treaties from the NPT to New START's lapse in February 2026." },
  { slug: 'escalation-ladder-kahn', game: true, sub: { nuclear: 'playground' }, cat: 'nuclear', sites: ['deterrence'], title: "Kahn's Escalation Ladder", status: 'live',
    blurb: "Step through nuclear crises from Cuba 1962 to Russia 2022 and India–Pakistan 2025 on Herman Kahn's 44-rung ladder, compare them, and read why the ladder misleads." },
  { slug: 'deterrence-lab-general', game: true, cat: 'gametheory', sites: ['deterrence'], title: 'Deterrence Lab', status: 'live',
    blurb: 'Move the costs and beliefs in three classic deterrence models (audience costs, costly signals and salami tactics) and test them against sourced crises from Fashoda in 1898 to NATO\'s eastern flank in 2016–17.' },
  { slug: 'ukraine-air-war', sub: { regions: 'ukraine' }, cat: 'regions', sites: ['deterrence'], title: "Ukraine's Air War", status: 'live',
    blurb: 'Russian missile and drone launches against Ukraine since 2022, by weapon type, with the share the Ukrainian Air Force reported shooting down.' },
  { slug: 'russia-nuclear-signals', sub: { regions: 'ukraine' }, cat: 'regions', sites: ['deterrence'], title: "Russia's Nuclear Signals", status: 'live',
    blurb: 'Every major Russian nuclear signal since February 2022, sourced and scored by what it changed, set against Western responses and the course of the war.' },
  { slug: 'red-sea-hormuz', sub: { regions: 'mideast' }, cat: 'regions', sites: ['deterrence'], title: 'Red Sea & Hormuz Pulse', status: 'live',
    blurb: 'Daily ship counts through Bab el-Mandeb, Suez and Hormuz from IMF PortWatch, against a sourced timeline of Houthi attacks, strikes, pauses and the 2026 Hormuz mining.' },
  { slug: 'war-markets', cat: 'gametheory', sites: ['deterrence'], title: 'War Markets', status: 'live',
    blurb: 'What prediction markets priced for strikes on Iran, ceasefires and a Russia–NATO clash in 2026, set against how each contract resolved.' },
  { slug: 'crisis-stability', game: true, sub: { nuclear: 'playground' }, cat: 'nuclear', sites: ['deterrence'], title: 'Crisis Stability Calculator', status: 'live',
    blurb: "Set two notional force postures and see Kent and Thaler's first-strike stability index: who gains by striking first, and how MIRVed silos, alert rates and launch under attack move it." },
  { slug: 'entanglement', game: true, sub: { nuclear: 'playground' }, cat: 'nuclear', sites: ['deterrence'], title: 'Nuclear Entanglement', status: 'live',
    blurb: 'Plan a conventional campaign against satellites, command links, launchers and bases that also serve nuclear forces, and watch use-or-lose pressure, misread warning and the fog of war push a notional escalation risk up, then test the fixes the literature proposes.' },
  { slug: 'warhead-ambiguity', game: true, sub: { nuclear: 'playground' }, cat: 'nuclear', sites: ['deterrence'], title: 'Is It a Nuke?', status: 'live',
    blurb: 'Your sensors report an incoming missile that could carry either warhead: update on context, launch site and trajectory, then wait, hit back conventionally or launch on warning, and see how priors and entanglement produce false alarms.' },
  { slug: 'nuclear-tests', sub: { nuclear: 'facts' }, cat: 'nuclear', sites: ['deterrence'], title: 'Every Nuclear Test', status: 'live',
    blurb: 'Explore all 2,056 nuclear tests since Trinity by state, environment, yield and test site, reconciled against the ACA, SIPRI and DOE counts and the treaties that drove testing underground and then stopped it.' },
  { slug: 'declaratory-policy', sub: { nuclear: 'facts' }, cat: 'nuclear', sites: ['deterrence'], title: 'Who Promises What', status: 'live',
    blurb: "No-first-use pledges, security assurances, conditions for use and alert postures for all nine nuclear-armed states, quoted from their own documents and dated, with 'not declared' where no official statement was found." },
  { slug: 'game-theory-gallery', cat: 'gametheory', also: ['deterrence'], sites: ['deterrence'], title: 'Game Theory Gallery', status: 'live',
    blurb: "Move the costs, beliefs and balance of power in eight classic game-theory models of war and cooperation, from Fearon's bargaining range to Schelling's brinkmanship, and watch the equilibrium change, with every result cited to its source." },
  { slug: 'ukraine-support', sub: { regions: 'ukraine' }, cat: 'regions', sites: ['deterrence'], title: 'Who Supports Ukraine', status: 'live',
    blurb: 'Who pledged aid to Ukraine and how much each donor has allocated: military, financial and humanitarian support by donor since 2022, in euros or as a share of GDP, from the Kiel Institute.' },
  { slug: 'proliferation-paths', sub: { nuclear: 'facts' }, cat: 'nuclear', sites: ['deterrence'], title: 'Proliferation Paths', status: 'live',
    blurb: 'Explore 1939 to 2017 to see which states explored, pursued, acquired and gave up nuclear weapons, as three published datasets code it, with every disagreement between them shown.' },
  { slug: 'treaty-tracker', sub: { nuclear: 'facts' }, cat: 'nuclear', sites: ['deterrence'], title: 'Treaty Tracker', status: 'live',
    blurb: 'Twenty nuclear and arms-control treaties, 197 states, 1963 to 2026: explore the years to see who signed, joined, suspended or walked away, with every date traced to a depositary record or official statement.' },
  { slug: 'kharg-island', game: true, sub: { models: 'wargames', regions: 'mideast' }, cat: 'models', also: ['regions'], sites: ['deterrence'], title: 'Kharg Island', status: 'live',
    blurb: "A notional, dice-driven wargame of a U.S. move on Kharg Island, Iran's oil export hub: seize, raid or blockade it, watch every roll, then see how 1,000 games trade success against escalation and oil prices." },
  { slug: 'iran-enrichment', sub: { nuclear: 'facts', regions: 'mideast' }, cat: 'nuclear', also: ['regions'], sites: ['deterrence'], title: "Iran's Enrichment Clock", status: 'live',
    blurb: "Iran's enriched uranium from every IAEA quarterly report since 2016, against the JCPOA limit and quoted breakout estimates, to the June 2025 strikes after which there is no verified figure." },
  { slug: 'hormuz-mcm', game: true, sub: { models: 'budget', regions: 'mideast' }, cat: 'regions', also: ['models'], sites: ['deterrence'], title: 'Hormuz Mine Clearance', status: 'live',
    blurb: 'Set the mines, clutter, forces and threat, and see how long it takes to clear shipping routes through Hormuz and how much risk remains when they are declared clear.' },
  { slug: 'rhetoric-global', cat: 'tracking', sites: ['narratives'], title: 'Rhetoric Heatmap: Russia and Beyond', status: 'live',
    blurb: "What the Kremlin and Iran's Foreign Ministry keep saying, week by week since 2021: recurring formulas from 'special military operation' to 'Zionist regime' as a heatmap, with every quote one click from its source." },
  { slug: 'rhetoric-search', cat: 'tracking', sites: ['narratives'], vault: 'rhetoric', title: 'Rhetoric Search', status: 'live',
    blurb: 'Search official statements and state media from Russia, China, Iran, North Korea, Belarus, the U.S., Pakistan and India: official sentences quoted, media listed by headline. A Trends view tracks tone, stance, topics, alerts and cross-country echoes over time.' },
  { slug: 'raid-night', game: true, sub: { models: 'wargames', regions: ['ukraine', 'mideast'] }, cat: 'models', also: ['regions'], sites: ['deterrence'], title: 'Raid Night', status: 'live',
    blurb: 'Defend four notional cities through three real-time waves of drones and missiles modelled on real raids, and watch the cost exchange as your interceptors run out.' },
  { slug: 'matrix-game', game: true, sub: { models: 'wargames', regions: 'ukraine' }, cat: 'models', also: ['regions'], sites: ['deterrence'], title: 'Baltic Matrix Game', status: 'live',
    blurb: 'An argument-based matrix wargame of a fictional Narva crisis: argue an action with three reasons, face counter-arguments, and roll 2d6 over six turns.' },
  { slug: 'sub-hunt', game: true, sub: { models: 'wargames' }, cat: 'models', sites: ['deterrence'], title: 'The Hunt', status: 'live',
    blurb: 'Hunt a hidden submarine in the Greenland–Iceland–UK gap: spend each turn\'s effort on buoys, aircraft, helicopter and ship, learn how it moves, and pounce.' },
  { slug: 'fog-of-command', game: true, sub: { models: 'wargames' }, cat: 'models', sites: ['deterrence'], title: 'Fog of Command', status: 'live',
    blurb: 'Defend or attack a fictional valley crossing against a commander who acts only on what it can see. Feint, bait, hit flanks, and spot your artillery with recon.' },
  { slug: 'defense-in-depth', game: true, sub: { models: 'wargames' }, cat: 'models', sites: ['deterrence'], title: 'Defense in Depth', status: 'live',
    blurb: 'Hold or break a fictional trench front: site machine guns for enfilade, leapfrog under the barrage, and time the counterstroke. Division to army scale, 1917–18 or modern, with a learning campaign.' },
  { slug: 'orbital-denial', game: true, sub: { models: 'wargames', nuclear: 'playground' }, cat: 'models', also: ['nuclear'], sites: ['deterrence'], title: 'Orbital Denial', status: 'live',
    blurb: 'Jam, dazzle, hack or shoot down a notional rival\'s satellites over a 10-month crisis and war, then see what your debris costs both sides for decades, with the escalation risk you ran.' },
  { slug: 'will-to-fight', cat: 'gametheory', sites: ['deterrence'], vault: 'dissertation', title: 'Will to Fight', status: 'live',
    blurb: 'A two-level model of resolve and cohesion: why some armies collapse overnight and others hold, with case presets from Kabul to Ukraine.' },
];

// The narratives site carries only entries that name it; entries without `sites` are on tsm and deterrence.
export const onSite = (x, site = SITE) => (x.sites ? x.sites.includes(site) : site !== 'narratives');
/** A tool's category on a given site (siteCat overrides cat per site). */
export const catOn = (t, site = SITE) => (t.dev && site === 'deterrence' ? 'dev' : (t.siteCat && t.siteCat[site]) || t.cat);
const ORDER = { deterrence: ['gametheory', 'nuclear', 'regions', 'narratives', 'models', 'tsm', 'dev'], narratives: ['tracking'] };
// `also` lists extra categories a tool appears in; `cats` is its primary category plus those.
const forSite = t => ({ ...t, cat: catOn(t), cats: catOn(t) === 'dev' ? ['dev'] : [...new Set([catOn(t), ...(t.also || [])])],
  blurb: (t.siteBlurb && t.siteBlurb[SITE]) || t.blurb });
// `unlisted` tools are still built (old links keep working) but leave menus and landing pages (superseded tools).
export const TOOLS = ALL_TOOLS.filter(t => onSite(t) && !t.unlisted).map(forSite);
// Published builds replace this with the Coming Soon entries, encrypted with the Coming Soon password
// (scripts/build_site.py); in the source tree the entries are simply in ALL_TOOLS above.
export const DEV_SEALED = "htN0s/4Lc5vm6f2t5NaHPscoozVT4Mr3VNwEh26WkbMHNMSYaoqqG1+Of5bsz5+xRmSydWDwqUlW80NiMVFM/sFUcvOxrf7hVQpLG7v/XhFZPkv5NWE2SVwEW4zUVYGPHLemErUjFCWkfgX0KqkjUUEhFbxdQ62hdVAnW0gA64+nQKKP0If9epGYSkDsTMZVoskgK2UEg197TBPNOT0xdkIdHrqgeUDBHtC1xiWIe+ptD1CiH0bGxDVqXQJjyGlqv3eBo0YlVb9h9qrevvW3uZL+ZymJzYbriEhQpTrKjwHeoUIEjSzS9zQc/4s9mfv6075xCFXrG6hsAPL5ksmqBy/LfZwnSv8mkUSdUiopqc8cd0X6nvpd3zJp6cU9aVztWSbVZEOWhG+EH5r82f/Beg6ErbwYpYf8BTG98YpD/7hB362agcWVfg4IvnIblzY7SXikK2He9h9KzOSrK5W+XUqGQXbtO05XiqZ5qT7iypM//S0sa7HI3PbB0rApTyWWhM4jdwGjt6qksAgg3F89+aK2teITp3YBJ2tvhKWnuZ4xDZfZvRmlMhC/rVbFV6QhjItT7MqgTxO5so0Y4tewGFlLtPnZqlGbUHrmn57RDloBrVGi8sr6CzsSYgG4xJcc6kwBqiptOAPv3LAPTE3zHI44pc6KZ8KYPHBrzEhs19kplojYFh6rYB9Fi2xAYimzTEtVrmZh53QgHzjgIqXM4YOWP2GHRIwgmq+LubomQeT8k4+kK0mo2pJciyGditn00hKoZ/t/uqroAFxNjni1aNagFrJvTjchMwc783DnXS7rRjUnabfLFO9eRczC0xJp3NHLLm/in8aG4kk8v3qEKp79h3sMLluxOAnxsz1n8PBeF6Y1Hx/Myf42OltI7eanRrUkC+o702RINsDFe9PWq0SuH6bNkDEOSYOkFjtdk6i8np8Os+llg3TDGGly21zEkwbSN+wQiD6fG5J7bvouvbwysvgghSBGKTze27eqeLsrRSuWZ3ZM3u1kmPNgXZ/VwGpEOFCUcLqYhOMZ2ippsEP+7/Kyc/QUc8ZMW1a+zfJ3X9wABtM4VJjQMUTsyQeO3/APU69rmhy855soW1yT6UmSEl5ghi+Hm6dY7UXzQahKQqvPlHV+R9XuqvoDG3HKf0hewp0SFyLOJQzsccaTljuoqKdO6PkxNjPucumfvZ4bQTsXTgbGzbHbGUuRB9OcbtPq1NGlSjqbFIIHxDDWRkfUdIxtxTlB540nN6wT5/YtHid4mYp3x8qHk5t/57COwdt3UQvryf7cWIjrq0oT0XLb3aMgrSgcaSsxRCgrrDAjZd66M31WxVpIZEAHESJaCXwIJWgxZm6nYa2rrofp9O8vi+k/Rax1XfiJDBzSX5L934JJH+kcwATRrmZWjMCxyo1ZqqlxashBZKSPfPkprY3hCLgJs05fqTF01TGgCWa6olpL/HWM7QU0ALu4dW3Xc8UWWr9ATJtQB8uzaK6s8b2VajXAUTxhqAWeJCA/hX8B1M1vGPrASGzXiUkegQXxFbjfViHaCmgAlVeAlX9kzxQia2XW8h9Q//02SVZRQE8MXI7D+YQHsIkbfAxjl7Rs54QtYep74ztGetORKoAyOH9iFHbdjMA+q71lT7p0Um7r+OldwYbg2KaAydUbR/sCe2KttQhMap9zb2gFpVEqtvJZDv4lsi/Bf5rC18IoTXDLUtcbAZS0VR5+/E09AYIvlW3rpGjL8OpcvXxHa70jF2Rf5RDsUjBE3GuYWPRtJr6zI/QbDPLqGGug1soOiAL5zsVwW9S/mRsvV0DSLeeWzcNWQeEVtKUil16cBuYODDct8baqXtNgFauZI2EKiQ15296lv1qnR4pvsf8SjLDphJPppUntVExA9a74BwEy4ZaNbtFMo+EkfRvVADcB2FxRqI/1faFCuHrwgk4U9m1o+6/zbw3pmgzYVD5ZTxnpulDcdGrxeB9eRWSzUtZvuJpUsxnKHxHLxOXMj9iSIGFRwaYnKiyYHSQeJolghDt8CagD1Qqckiwwxxj5E2UNY+G8Fb2Yy2cok5K2o+M6KrvnL5Bl6iHq6SjJvpeNuEoetUO/+frr7i9suAAgPN6rQHQmqto0CqgJxWcoi6jp2pYrDOXVd/C6qGK47T3l10i0r3ZrSDxYTsL1cIoLINAGD+akjhbE+s4/bwD+mXIhX/rdqNF+ELgWF2cQFq1LWIIRdcek2UoizGSU3/zZNGSiggDZN+NZzntAJc31XDv1TB5gPbCgm8313LgAS8qjX1XFtKrRsYxnwAYo5fp4fvShHYxVNd0I3vjsWKon+PVvombyXWRzGIb4GJJnmJe5c+lSlT8wM/qmJ/JKNH3wEKfvk5SxdgfaLPgwmk9EA3aVQO7DIRhognw+rZjre2uP39VBCN3P5T3GQhh96m89BmT2KInxpqI4VOOzsgiF7AP0C3pgFvIa2eTysdO4p9KoriQok4x2IMLr53cT0wXBNcmyE6jcVBtZuf7xJgzLLeAeCC3wJR6UWtLVviC1ytOK0frOVlwS5lcgfZ/HiZAmd+6YCSW9Rt/59EazA+IC9FLo1qobthR5mny+hqSj2aGe0c45/8rppTDV/XDtDSu1zr9KYpLgesJVmU4NUOmplXkdLLdMVXcflOEzWhxZ3mUc8g/ZeFUixNGauqGke5bKskjei6k2v+jc2DrlXi7HMdfAUMWVES3xOotJoV3KLhdK0JZKHgpQTNS9tx5XIsFl6/pMi9bX/R9EZPfjkfCXdGT4uFj2vbzTZvSpmQHmHLz3SM2OmLlwwMH/HJXsp9pbdY1a2XR4fOc515+rBi+WGm74oY0N/UWb1tRMUIvmuHv54YG8D9j+GqKEUTRlvJQy7gFmK3d37jJqXtBSSL9cJfHniNe3svsqbUARtr8zCO98pab2jCAyu49zJVdZH/Z45ZmOZJHG2lVmhebjtfm4CPKfECn8p5w+0tuhocoqtZ6sVyk55Nl1dATvNLlpSBzJl22goyZCFvkGsottaFBjVLdZVHQzv8Mrpmn+ac79rkSIg/X3D0JGmu5z9zSX4MUb4gw1arUacm4kAZHRFOfqIF1T3X1aR6TUENXF4fUg3GYq6cSz0CysF6ppeBY+W8gtPJtkvc5IJcMdEYqn+j60X4igiR+W3HJkHVNHoBcQcSLUQE/IVekVMdG1OHfetq+E6TnMmCbtLzT0eHVwaldZwYT9GXhl07YHKw0OL/kD+fXbNTW+kby7AVG2pyVp+/t5UXlpVO1ZWM7S6g1zkahT7Rqpz3kg1Jc+W94Rn2LknOYK30OFgYy7DQjoo4qHan8KkDTpUGHNm4tyqa4AHh+O1ALv0tAXObSPuXOAXSEL4rQin6ll7FK/tVj5gnQhGgWY7TTBGiphSnNSZAMXeWlDgwH1diU7r7GlFPCbRawHPouFOxIojzNWq3MM8TELk25ws7h94Uerr9R2RlAP/Ef8T01HZ0kcNAOycYShNdhizD7m0J+rSrBHJUA8JeT5MXwXhr1egsJsgvY/nBvsj1/gXAV3j6EAVf54BOSJHSpHSPj04hQ+PQQHc6HxW2FM2IgNScS9kfleSjPYUavyemgswNz27NyjSR2CkAtJiVJZT4AxgWQN3ebapopue6DKWoMclJXm6bJelC5OtlYLxCEI2XRZ2qYo6WdbQiR2eoshKOlmDfC8mnhmxB+HBy4+6t15lsz5wjZS+EZWdpOcTh352D5c3V/0vCDDtE2M+4+VI+JLdrQsQgQWL7OChzIx+q5l9IupKr2qwV+2Xafb+pECQAs9p+l8akMEVjDkHaz7Y2TRv/RimkTkum0sKgKyIjzvys0734FaxO5JrmWbp+iphAJDWlviWC8RpZHTe/FrrmQ/g8JqX35cKDOfWUcF23/0Lero1Bu5SP+vFth8lQVeKGYIRhFk+gTt/GeIoraCw1Aj9VpGpfp0QHXb2dQLFGTGTOlV5fZWSxDPsON/dvP/UlF6I/E9ecQKnlFPtrAYrXTBgcRzPq84aV1iZQNTJsjY2pm2HHRwgI4mTuNCS80xzl/t+10xbmLshEPp9uEIWKZYL+cYUMaQ2hYbH0w/FZZTvpTuqNh/+eBKz5AY1ueAOdUQMzJXb1JJM3B9axl1nFJztAL//UU0/9F5MmIVXZCFn2jNj/GoeaMGb7HGzPNGe1h5SjYzMeMLchVE95ZdLbhoHs63It0BbzmWp1UIXJgF0ZNDjIu+i4jnn98aN4SFbZwsIKuC7K1uXT4H7S+Z4gFXMbwinwgkUD4m4rortjjx0k9jycqiHPMndBAScTtzicWyqyQBh79fucjNH8vPkJ2E+81VRZqBdKUbd4RdBw6eRbaL49JqKoda/HW04jlAAzkAwNoNrgi+3c87j9CuDqQFiDd143fQtBpziI3aTbmyVX0K64TW9LObyMEV4twI9pT9C+46R85IEr/Ma6GdtSw7oZuzy6ZqHp0PUo5r3OxmqepMYroEmD3EmDkG0A0KhZflhtk9GxuAyXCE9SCBGLl6FIYgvqIwCpLn5YM+oG+Ysdjr05YK/zo4Q1IfrwSS6qH0cKSXp3wWd97GNsg86vEDHz1j2N1NQ0EKa8lzKLKFQlTFoNjWkK/ZI+30uHZaloyzDvZbWLHUci7bz0c30Xty9mAAI5Urc6TUVCidgPITagAR0E2upZvDBplfgBnvEOU1Mtm6SdepNdUUON1X+treP9Y0AzrD6GUSXQf6gZhcwJ6n1qs+qPp+GtfuUsojFvzxTcsObU59KW0rVpv6SzqYjoN3KWoQrlrK87tmoh5UipTHDUaSTZ35MBNHuPFRUte61PphiQ+CNU+kIRmz6aA+GYwlFJh0nsDuZNRE4NzusIH01nhYW6HbcPxmZnNGD2xgAdhdhgmXwC9wr22lpMQpXYHfaeqnmdtaz9nBpWc5D0NC5wlePDbzi4RJ6KXwB72QgmXLiHoc3uOUruxj6ADop1oOyoc+QS7KhIjXeFRPPTF3IWGlkd9GltXdgrB1T2vjdFATcpsoI2bBHe5M0J5hvVhhhHKZG/6gC56iHd2l3/++8uZrk8ThtgssGWyJPd8IAI0W7fbunMlr+ieKVjr3RXcg3QDO8v2QrpTYf8BI6dyfQTUNZB/M28KMY9/IINdTGluyD2ADzcpzMiwu4meCZigSEWYyfMvHIzw=";
/** Add tools decrypted from DEV_SEALED to the lists every page reads. */
export function addTools(list) {
  for (const t of list) if (!ALL_TOOLS.some(x => x.slug === t.slug)) { ALL_TOOLS.push(t); if (onSite(t)) TOOLS.push(forSite(t)); }
}
export const inCat = (t, id) => t.cats.includes(id);
const rank = c => (ORDER[SITE] ? ORDER[SITE].indexOf(c.id) : -1);
// Only categories with a tool on this site; the deterrence site uses its own order.
export const CATEGORIES = ALL_CATEGORIES.filter(c => onSite(c) && !c.hidden && ((c.sealed && DEV_SEALED) || TOOLS.some(t => inCat(t, c.id))))
  .sort((a, b) => (ORDER[SITE] ? rank(a) - rank(b) : 0));
